### ISSUE TITLE
latin-bert available from huggingface?

### ISSUE THREAD

**Issue by pstroe** [dbamman/latin-bert#4]
hi again,

small question: would you consider pushing latin-bert to the huggingface hub? another library I'm using "draws" the model directly from the hub, and if latin-bert would be in there, it would greatly simplify things. otherwise i would have to make quite some changes to make latin-bert work from within the other library.

best, phillip

**Comment by diyclassics** [comment]
Working on it... will update (hopefully) soon.

**Comment by andbue** [comment]
Hi there, I had a similar problem and ended up reverse engineering the SubwordTextEncoder from tensor2tensor with regular expressions in order to use it in huggingface. I don't know if this is the best or even most simple solution, but the first results seem to indicate compatibility. Some more tests with the original training data might be necessary to make sure the results of the tokenizer do not differ too much from those of the original one.

Simply pushing the model and tokenizer to the hub with push_to_hub did not feel right (since I did not train it) – but feel free to use the files at [andbue/latin-bert-huggingface](https://github.com/andbue/latin-bert-huggingface) to that end if you want!

**Comment by diyclassics** [comment]
Exciting!—I had minimal luck with this process in a past attempt. Will review this week and let you know how it goes.

**Comment by LuisAVasquez** [comment]
Any update on pushing it to the hub ?

[This tutorial from HuggingFace](https://huggingface.co/blog/how-to-train) seems to have everything needed to easily train a BERT tokenizer and a model from scratch.
